repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      - id: ruff-check
        files: ^(app|src|tests)/
      - id: ruff-format
        files: ^(app|src|tests)/